services:
  wordpress:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: maddieks_wordpress
    depends_on:
      - db
    ports:
      - "8080:80"  # Map WordPress to localhost:8080
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./themes/maddieks:/var/www/html/wp-content/themes/maddieks  # Mount your theme
      # - ./20251002/uploads:/var/www/html/wp-content/uploads
      # - ./20251002/plugins:/var/www/html/wp-content/plugins
      # - ./wp-config.php:/var/www/html/wp-config.php
    networks:
      - maddieks_wp_network

  db:
    image: mariadb:latest
    container_name: maddieks_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
      - ./20251002/db:/docker-entrypoint-initdb.d
    networks:
      - maddieks_wp_network

networks:
  maddieks_wp_network:
    driver: bridge

volumes:
  wp_data:
  db_data:
  wp_uploads:
