services: 
  db:
    image: mariadb:10.6.4-focal
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    expose: 
      - 3306
      - 33060
    ports:
      - 3306:3306
    networks: 
      - app-network

  wordpress: 
    image: wordpress:6.1.1-fpm-alpine
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
      - ./maddieks:/var/www/html/wp-content/themes/maddieks
    restart: always
    ports: 
      - "9000:9000"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
    networks: 
      - app-network
  
  webserver: 
    depends_on: 
      - wordpress
    image: nginx:1.23.3-alpine
    container_name: webserver
    restart: unless-stopped
    volumes: 
      - wp_data:/var/www/html
      - ./maddieks:/var/www/html/wp-content/themes/maddieks
    networks:
      - app-network
    ports: 
      - "3000:80"
  
  # phpmyadmin: 
  #   image: phpmyadmin/phpmyadmin:latest
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306
  #   ports: 
  #     - "8081:80"
  #   depends_on:
  #     - db
  
volumes:
  db_data:
  wp_data:

networks: 
  app-network: 
    driver: bridge

